parameters:
- name: job_id
  type: string
  default: 'deploy_agent'

- name: image_type
  type: string

- name: agent_pool
  type: object
  default:
    name: 'Default'

- name: managed_image_name
  type: string

jobs:
- job: ${{ parameters.job_id }}
  displayName: Deploy Agents (${{ parameters.image_type }})
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 30
  pool: ${{ parameters.agent_pool }}
  variables:
  - group: 'Image Generation Secrets'
  - template: variables-common.yml

  steps:
  - checkout: self
    clean: true
    fetchDepth: 0
    fetchTags: false

  - task: AzureCLI@2
    displayName: 'Deployment | bicep'
    inputs:
      azureSubscription: ${{ variables.SERVICE_CONNECTION }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create `
        --resource-group ${{ variables.AZURE_RESOURCE_GROUP }} `
        --name deploy-agents-${{ variables.LOCATION }} `
        --template-file 'source/azuredeploy.bicep' `
        --location '${{ variables.LOCATION }}' `
        --parameters adminUsername=${{ variables.ADMIN_USERNAME }} `
        --parameters generateNewKey=true `
        --parameters imageName=${{ parameters.managed_image_name }}
