parameters:
- name: job_id
  type: string
  default: 'deploy_agent'

- name: image_type
  type: string

- name: agent_pool
  type: object
  default:
    name: 'Default'

- name: managed_image_name
  type: string

variables:
- group: 'Image Generation Secrets'
- template: variables-common.yml

jobs:
- job: ${{ parameters.job_id }}
  displayName: Image Generation (${{ parameters.image_type }})
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 30
  pool: ${{ parameters.agent_pool }}
  variables:
  - template: variables-${{ parameters.image_type }}.yml

  steps:
  - checkout: self
    clean: true
    fetchDepth: 0
    fetchTags: false

  - task: AzureCLI@2
    displayName: 'Deployment | bicep'
    inputs:
      azureSubscription: $(SERVICE_CONNECTION)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create `
        --resource-group $(AZURE_RESOURCE_GROUP)
        --name deploy-agents-$(LOCATION) `
        --template-file 'source/azuredeploy.bicep' `
        --location '$(LOCATION)' `
        --parameters adminUsername=${{ variables.ADMIN_USERNAME }} `
        --parameters generateNewKey=true `
        --parameters imageName=${{ variables.ManagedImageName }}
