parameters:
- name: managed_image_name
  type: string

trigger: none
pr: none

jobs:
- template: agent-deployment.yml
  parameters:
    image_type: ubuntu2204
    managed_image_name: ${{ parameters.managed_image_name }}
