schedules:
- cron: "00 12 * * Sun"
  displayName: Sunday 22:00 (UTC + 10) Australia Eastern
  branches:
    include:
    - main
  always: true

trigger: none
pr: none

jobs:
- template: image-generation.yml
  parameters:
    image_type: ubuntu2204
    image_readme_name: Ubuntu2204-Readme.md
    image_template_name: ubuntu-22.04.pkr.hcl
